name: Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      # Every push on those branches
      - main

permissions:
  id-token: write
  contents: read

jobs:
  run_unit_test:
    runs-on: ubuntu-latest
    name: PyTest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          persist-credentials: false

      - name: Python Setup
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 #v7.0.0
        with:
          python-version: '>=3.5'

      - name: Run Python Tests
        run: |
          pip install -r requirements.test.txt
          python -m pytest --ruff
